//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAlumniPortalMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlumniEntities : DbContext
    {
        public AlumniEntities()
            : base("name=AlumniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Contact_Us> Contact_Us { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<tblCity> tblCities { get; set; }
        public virtual DbSet<tblCountry> tblCountries { get; set; }
        public virtual DbSet<tblStudentEvent> tblStudentEvents { get; set; }
        public virtual DbSet<tblUniversityCampu> tblUniversityCampus { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<tblClass> tblClasses { get; set; }
        public virtual DbSet<tblEmployed> tblEmployeds { get; set; }
        public virtual DbSet<tblWife> tblWives { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<SalaryRecord> SalaryRecords { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<FeeRecord> FeeRecords { get; set; }
    }
}
