//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAlumniPortalMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.tblStudentEvents = new HashSet<tblStudentEvent>();
        }
    
        public int ID { get; set; }
        public string Event1 { get; set; }
        public string DateofEvent { get; set; }
        public string PlaceofEvent { get; set; }
        public string Photo { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<tblStudentEvent> tblStudentEvents { get; set; }
    }
}
