//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAlumniPortalMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeRecord
    {
        public int ID { get; set; }
        public string StudenName { get; set; }
        public string FatherName { get; set; }
        public string Section { get; set; }
        public string RollNo { get; set; }
        public Nullable<int> UniversityCampusID { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public string BasicFee { get; set; }
        public string AdmissionFee { get; set; }
        public string TotalFee { get; set; }
        public string PaperFund { get; set; }
        public string Misc { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> PayableInDueDate { get; set; }
        public Nullable<int> PayableAfterDueDate { get; set; }
        public Nullable<int> classID { get; set; }
        public string Description { get; set; }
        public Nullable<int> StudentID { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual tblClass tblClass { get; set; }
        public virtual tblUniversityCampu tblUniversityCampu { get; set; }
    }
}
