//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAlumniPortalMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClass
    {
        public tblClass()
        {
            this.Students = new HashSet<Student>();
            this.FeeRecords = new HashSet<FeeRecord>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<FeeRecord> FeeRecords { get; set; }
    }
}
