//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAlumniPortalMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCity
    {
        public tblCity()
        {
            this.Students = new HashSet<Student>();
            this.Teachers = new HashSet<Teacher>();
        }
    
        public int ID { get; set; }
        public string cityName { get; set; }
        public Nullable<int> countryId { get; set; }
        public bool Is_Active { get; set; }
        public bool Is_Delete { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
        public virtual tblCountry tblCountry { get; set; }
        public virtual ICollection<Teacher> Teachers { get; set; }
    }
}
