//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAlumniPortalMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUniversityCampu
    {
        public tblUniversityCampu()
        {
            this.Students = new HashSet<Student>();
            this.Students1 = new HashSet<Student>();
            this.FeeRecords = new HashSet<FeeRecord>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Photo { get; set; }
        public bool isActive { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<Student> Students1 { get; set; }
        public virtual ICollection<FeeRecord> FeeRecords { get; set; }
    }
}
