//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAlumniPortalMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CellNo { get; set; }
        public string Address { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string BasicSalary { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string MaritalStatus { get; set; }
        public string Religion { get; set; }
        public string Description { get; set; }
        public Nullable<int> UniversityCampusID { get; set; }
        public string RecentDegree { get; set; }
        public string JobExperience { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Designation Designation { get; set; }
        public virtual tblCity tblCity { get; set; }
        public virtual tblCountry tblCountry { get; set; }
    }
}
